### ISSUE TITLE
Cajita num'erica de la absortancia

### ISSUE THREAD

**Issue by AltamarMx** [JaelSantos01/EnerHabitatShi#11]
Cuando seleccionas algo de la lista de absortancia y se carga el valor num'erico en la caja de valores, si das click en las flechas hace cosas raras. Seg'un yo, es por qu'e el paso del valor es muy alto, ponlo en 0.01 y me cuentas que pasa, pero tiene comportamientos raros.

**Comment by JaelSantos01** [comment]
Este issue no lo comprendo muy bien

**Comment by AltamarMx** [comment]
la caja donde aparece el valor numérico de la absortancia se porta raro cuando mueves las flechas de los valores. Creo que es por qué el paso en el que se modifican los valores está en 1, pero hay que revisar como se comporta.
