### ISSUE TITLE
noticias

### ISSUE THREAD

**Issue by AltamarMx** [JaelSantos01/EnerHabitatShi#6]
Agregar que al definir algun True en el código, ponga este anuncio, para que se puedan personalizar anuncios al inicio de la webapp.

Tomar ejemplo de aquí:
https://gallery.shinyapps.io/respiratory_disease_pyshiny/

Código fuente:
https://github.com/rstudio/shiny-gallery/tree/master/respiratory_disease_pyshiny

**Comment by JaelSantos01** [comment]
que ponga alertas en cada movimiento o al iniciarse la webaap?

**Comment by AltamarMx** [comment]
al iniciarse, tal cual como lo tiene la página
