### ISSUE TITLE
documentacion

### ISSUE THREAD

**Issue by AltamarMx** [JaelSantos01/EnerHabitatShi#7]
Que en el panel de documentación que existe ahora, aparezca texto que esté alojado en un archivo o funcion o algo  para que pueda ser modificado, el código fuente de un ejemplo está en:
https://github.com/rstudio/shiny-gallery/tree/master/respiratory_disease_pyshiny

de la webapp de ejemplo de:
https://gallery.shinyapps.io/respiratory_disease_pyshiny/

**Comment by JaelSantos01** [comment]
que haya un documento en link para que ahi se agregue la documentacion?

**Comment by AltamarMx** [comment]
qe haya, si se puede, un archivo de tezto plano donde pueda escribir ahí la documentación, si no, como está en la app, pero empecemos por ahí, recuerda empezar primero por esa parte, por la parte fácil.
